-- 000001_initial_schema.down.sql
DROP TABLE IF EXISTS reserve_movement CASCADE;
DROP TABLE IF EXISTS goal_contribution CASCADE;
DROP TABLE IF EXISTS goal CASCADE;
DROP TABLE IF EXISTS cost_item CASCADE;
DROP TABLE IF EXISTS cost CASCADE;
DROP TABLE IF EXISTS entry CASCADE;
DROP TABLE IF EXISTS item CASCADE;
DROP TABLE IF EXISTS budget CASCADE;
