import {
  Wallet,
  CreditCard,
  Home,
  ShoppingCart,
  Package,
  Zap,
  AlertTriangle,
  RefreshCw,
  X,
  Check,
  LineChart,
  Lightbulb,
  Truck,
  Folder,
  Shield,
  Circle,
  Plane,
  Car,
  Book,
  Target,
  Pencil,
  PartyPopper,
  Settings,
  Wand2,
  Sofa,
  Laptop,
  Gem,
  GraduationCap,
  Umbrella,
  Rocket,
  CircleDashed,
  type LucideIcon
} from 'lucide-react';

const ICON_MAP: Record<string, LucideIcon> = {
  // Existing Emoji mapping
  '💰': Wallet,
  '💳': CreditCard,
  '🏠': Home,
  '🛒': ShoppingCart,
  '📦': Package,
  '⚡': Zap,
  '⚠': AlertTriangle,
  '🔄': RefreshCw,
  '✕': X,
  '✓': Check,
  '📈': LineChart,
  '💡': Lightbulb,
  '🚚': Truck,
  '📁': Folder,
  '🛡️': Shield,
  '🛡': Shield,
  '🔴': Circle,
  '✈️': Plane,
  '✈': Plane,
  '🚗': Car,
  '📚': Book,
  '🎯': Target,
  '✏️': Pencil,
  '✏': Pencil,
  '🎉': PartyPopper,
  '⚙️': Settings,
  '⚙': Settings,
  '🔮': Wand2,
  '🛋️': Sofa,
  '🛋': Sofa,
  '💻': Laptop,
  '💍': Gem,
  '🎓': GraduationCap,
  '🏖️': Umbrella,
  '🏖': Umbrella,
  '🚀': Rocket,

  // String key mapping
  'Wallet': Wallet,
  'CreditCard': CreditCard,
  'Home': Home,
  'ShoppingCart': ShoppingCart,
  'Package': Package,
  'Zap': Zap,
  'AlertTriangle': AlertTriangle,
  'RefreshCw': RefreshCw,
  'X': X,
  'Check': Check,
  'LineChart': LineChart,
  'Lightbulb': Lightbulb,
  'Truck': Truck,
  'Folder': Folder,
  'Shield': Shield,
  'Circle': Circle,
  'Plane': Plane,
  'Car': Car,
  'Book': Book,
  'Target': Target,
  'Pencil': Pencil,
  'PartyPopper': PartyPopper,
  'Settings': Settings,
  'Wand2': Wand2,
  'Sofa': Sofa,
  'Laptop': Laptop,
  'Gem': Gem,
  'GraduationCap': GraduationCap,
  'Umbrella': Umbrella,
  'Rocket': Rocket,
};

export function getIcon(nameOrEmoji?: string): LucideIcon {
  if (!nameOrEmoji) return CircleDashed;
  return ICON_MAP[nameOrEmoji] || CircleDashed;
}
